SBmodel_name = 'test_pySBmodelJul23'
M_total = 1000000.0 #Msol
age = 1.2 #Myr
IMF_exponents = [1.3,2.3]
IMF_mass_limits = [0.1,0.5,120.0]
run_speed_mode = 'FAST'
Z = 'MW'
SED_library = 'FW'
spectra_library = 'WM'
rot = False
times_spectra_end = 50e6 #Myr
maximum_SN_mass = 40.
save_output = False
plot_ion_flux = True
plot_wind = True
plot_uv_slope = True
plot_ew = True
plot_colours = True
plot_SED_with_time = True
plot_hires_spectra = True
plot_SN_rate = True
plot_isochrones = True